# Site settings
title: SI2 PI Meeting 2018
email: rafsilva@isi.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "2018-meeting"
#url: "http://si2-pi-community.github.io"

# Build settings
markdown: kramdown

assets:
  sources:
    - fonts
    - images
    - assets/js
    - css

gems:
  - jekyll-assets

