# Site settings
title: SI2 PI Meeting 2018
email: rafsilva@isi.edu
description: > # this means to ignore newlines until "baseurl:"
  SI2 PI Meeting 2018
#baseurl: "/2018-meeting"
#url: "http://si2-pi-community.github.io"

# Build settings
markdown: kramdown

assets:
  sources:
    - fonts
    - images
    - assets/js
    - css

gems:
  - jekyll-assets

